# Generated by Django 5.1 on 2025-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='carga_horaria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
