# Generated by Django 5.1 on 2025-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disciplinas_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nome_sala', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('S', 'Sábado')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nome_curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CT', 'Curso técnico'), ('CAI', 'Curso de aprendizagem industrial'), ('CS', 'Curso superior'), ('FIC', 'Curso avulso')], max_length=255)),
                ('hora_aula', models.TimeField()),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=255)),
            ],
        ),
    ]
