# Generated by Django 5.1 on 2025-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambientes_cursos_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='hora_aula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='tipo',
            field=models.CharField(choices=[('CT', 'Curso técnico'), ('CAI', 'Curso de aprendizagem industrial'), ('CS', 'Curso superior'), ('FIC', 'Curso avulso')], max_length=3),
        ),
    ]
