# Generated by Django 5.1 on 2025-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cursos_codigo_alter_cursos_hora_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='hora_aula',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='sigla',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='tipo',
            field=models.CharField(choices=[('CT', 'Curso técnico'), ('CAI', 'Curso de aprendizagem industrial'), ('CS', 'Curso superior'), ('FIC', 'Curso avulso')], max_length=255),
        ),
    ]
